In [1]:
import numpy 

In [2]:
x = numpy.array([1,2,3,4])

In [3]:
print x

[1 2 3 4]


In [4]:
y = [2,3,4,5]

In [5]:
print y

[2, 3, 4, 5]


In [6]:
print x + y

[3 5 7 9]


In [7]:
print x * y

[ 2  6 12 20]


In [15]:
print numpy.dot(x,y) #dot product

40


In [16]:
xT = x.T #transpose 

In [17]:
print x.T + y


[3 5 7 9]
